name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2-VM-1-3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env: 
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.HOST_NAME }}
            USER_NAME: ${{ secrets.USER_NAME }}
            HOST: ${{ secrets.HOST }}
            
        run: |
          # Write the private key to a file and set permissions
          echo $PRIVATE_KEY >> secrets.txt
          echo $HOSTNAME >> secrets.txt
          echo $USER_NAME >> secrets.txt
          echo $HOST >> secrets.txt
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

          # Execute commands on the remote server
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << EOF
            echo "Deploying application..."
            cd ci
            ./actions.sh ${HOST}
          EOF
      
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
